# Generated by Django 5.0.6 on 2025-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_schedule_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.SmallIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
