# Generated by Django 5.2.7 on 2026-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinic_latitude_clinic_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='survey_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
